server:
  port: 8888
spring:
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: file://${user.home}/workspace/study/spring/micro-service/config-server/src/main/resources/config/licensing